version: '3.9'
services:
  app:
    restart: always
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:15.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - app

  migrate:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    entrypoint: ["python", "manage.py", "migrate"]

volumes:
  postgres-data:
