version: '3.9'
services:
  app:
    restart: always
    build: .
    command: gunicorn api.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80
    expose:
      - 80
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:15.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin2:
    image: dpage/pgadmin4
    container_name: pgadmin2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  migrate:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    entrypoint: ["alembic", "upgrade", "head"]


volumes:
  postgres-data:
