# Generated by Django 5.2.7 on 2025-10-28 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="githubrepo",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="githubrepo",
            name="github_id",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.RemoveField(
            model_name="githubrepo",
            name="private",
        ),
        migrations.RemoveField(
            model_name="githubrepo",
            name="user",
        ),
        migrations.CreateModel(
            name="UserGitHubRepo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("disabled", models.BooleanField(default=False)),
                ("private", models.BooleanField(default=False)),
                ("repo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.githubrepo")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "repo")},
            },
        ),
    ]
