# Generated by Django 5.2.7 on 2025-10-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_githubrepo_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usergithubrepo",
            name="private",
        ),
        migrations.AddField(
            model_name="githubrepo",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
